---

  - name: Install packages
    apt: name={{ item }} state=present update_cache=yes
    with_items:
      - g++
      - chromium-browser

  - name: "Install node dependencies"
    npm: path={{ app_dir }}
    become_user: "{{ ansible_ssh_user }}"

  # necessary for Mac hosts
  - name: "Rebuild SASS"
    command: "npm rebuild node-sass"
    become_user: "{{ ansible_ssh_user }}"

  - name: "Install s3_website gem"
    gem: name=s3_website user_install=no state=latest

  # so test runner can find browser
  - name: "Set path to Chromium"
    lineinfile:
      path: '/etc/environment'
      state: present
      regexp: '^CHROME_BIN='
      line: CHROME_BIN=/usr/bin/chromium-browser
