#!/bin/bash
set -e

function usage() {
    echo -n \
    "Usage: $(basename "$0")
    Run production build process."
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        docker-compose run --rm app run build:prod
    fi
fi
