#!/bin/bash
set -e

if [[ -n "${GIT_COMMIT}" ]]; then
    GIT_COMMIT="${GIT_COMMIT:0:7}"
else
    GIT_COMMIT="$(git rev-parse --short HEAD)"
fi

function usage() {
    echo -ne \
    "Usage: $(basename "$0")
    Run tests and linter.

      --jenkins \tAlso run linter with file output for Jenkins CI server to parse.\n\n"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        if [ "${1:-}" = "--jenkins" ]; then
            ANGULAR_LINT_CMD="lint:ci"
        else
            ANGULAR_LINT_CMD="lint"
        fi

        # Build and tag container(s)
        GIT_COMMIT=${GIT_COMMIT} docker-compose \
           -f docker-compose.yml \
           -f docker-compose.test.yml build

        echo -e '\nRunning tests...'
        GIT_COMMIT="${GIT_COMMIT}" docker-compose \
            -f docker-compose.yml \
            -f docker-compose.test.yml \
            run --rm app run test

        echo -e '\nRunning linter...'
        GIT_COMMIT="${GIT_COMMIT}" docker-compose \
            -f docker-compose.yml \
            -f docker-compose.test.yml \
            run --rm app run "$ANGULAR_LINT_CMD"
    fi
fi
