---
- hosts: app
  become: true

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes

  roles:
    - { role: "azavea.nodejs" }
    - { role: "azavea.ruby" }
    - { role: "azavea.java" }
    - { role: "climate-change-lab.app" }
