---
- hosts: app
  become: true

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes

  roles:
    - { role: "azavea.ntp" }
    - { role: "azavea.aws-cli" }
    - { role: "climate-change-lab.docker" }
    - { role: "climate-change-lab.environment" }
